### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by votmA** [kousheekc/nmpc_px4_ros2#2]
When I am trying to launch it from docker container.

I am getting this error

`[INFO] [rviz2-4]: process started with pid [206004] 

[odom_repub_node-1] [INFO] [1739208048.683370396] [odom_repub_node]: Republishing odom from PX4 to ROS2

[rviz2-4] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

[ref_traj_pub_node-2] [INFO] [1739208048.748178822] [ref_traj_pub_node]: Reference path with 10001 points found

[nmpc_flight_mode-3] [DEBUG] [1739208048.750934498] [nmpc_flight_mode]: Waiting for FMU...

[nmpc_flight_mode-3] [DEBUG] [1739208048.780788302] [nmpc_flight_mode]: Checking message compatibility...

[nmpc_flight_mode-3] [DEBUG] [1739208048.788750814] [nmpc_flight_mode]: Subscriber found, continuing

[nmpc_flight_mode-3] [DEBUG] [1739208048.889030387] [nmpc_flight_mode]: Publisher found, continuing

[rviz2-4] [INFO] [1739208048.915495030] [rviz2]: Stereo is NOT SUPPORTED

[rviz2-4] [INFO] [1739208048.916104978] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)

[rviz2-4] [INFO] [1739208048.944238205] [rviz2]: Stereo is NOT SUPPORTED

[nmpc_flight_mode-3] [ERROR] [1739208049.207421851] [nmpc_flight_mode]: Mismatch for the following topics, update PX4 or the px4_ros2 library 
and px4_msgs:

[nmpc_flight_mode-3]   - fmu/out/vehicle_local_position

[nmpc_flight_mode-3] terminate called after throwing an instance of 'std::runtime_error'

[nmpc_flight_mode-3]   what():  Registration failed

[ERROR] [nmpc_flight_mode-3]: process has died [pid 206002, exit code -6, cmd 
'/workspace/nmpc_px4_ros2_ws/install/nmpc_px4_ros2/lib/nmpc_px4_ros2/nmpc_flight_mode --ros-args -r __node:=nmpc_flight_mode --params-file /workspace/nmpc_px4_ros2_ws/install/nmpc_px4_ros2_bringup/share/nmpc_px4_ros2_bringup/config/nmpc_params.yaml'].
`

**Comment by votmA** [comment]
I have found out why it is happening. Actually you need to sync the px4_msgs px4-lib-interface and PX4-Autopilot to the versions where they are not in conflict with each other. 

I have used:

- PX4-Autopilot v1.15.4
- px4_msgs v1.15
- px4-lib-interface 1.4.0

It seems there is no more compatibility issue in messaging.

However I could not select custom flight mode. It states in PX4 docs, that it is needed to be QGC daily build. But this build does not work on my PC. 

May you @kousheekc provide info which versions have you used and which QGC?

**Comment by kousheekc** [comment]
Hi, that's the issue that I was suspecting as well. In my setup, I was using the "main" branch for all (PX4-Autopilot, px4_msgs and px4-ros2-interface library) with QGC daily build compiled from source. But apparently a recent commit on one of the three packages broke the compatibility. I will make some updates to use the "stable" releases of this package so that this issue does not persist. Once I make an update I will let you know in this thread.

**Comment by kousheekc** [comment]
Hi, I have pushed some changes to solve the issues. To summarise:

- px4_msgs uses the latest commit from branch "release/1.15"
- PX4-Autopilot uses the latest stable release "v1.15.2"
- Regading the custom modes not showing up with QGC Daily build: in my case I had compiled QGC from source, with the latest commit, using the container method. With this version the custom modes show up. I will try simply downloading QGC Daily Build and seeing if that works.

I have also updated the README with some changes to the installation process.

Do let me know if this solved your issue.

**Comment by votmA** [comment]
Hi @kousheekc ! I appreciate your help and work.

I have managed to start up everything, and in the last it was problematic to launch daily build. But I still don't see the custom mode in the selection panel. Here I have attached my screen. Maybe you can say something. Also there is visible output from your node.

![Image](https://github.com/user-attachments/assets/e4e20e21-1015-425c-8774-cc472adaf4c9)

**Comment by kousheekc** [comment]
Hi, unfortunately I am unable to replicate this behavior. See attached image. Can you confirm if you compiled QGroundControl from source?

![Image](https://github.com/user-attachments/assets/4b7af7ba-de37-400d-bfcf-1656679e8cac)

**Comment by votmA** [comment]
No I have downloaded daily build from the website.

**Comment by kousheekc** [comment]
Hi, so I have done some tests myself and it does appear that the latest daily build available on the internet does not show the custom modes. (This issue needs to be raised with the developers of QGC eventually). Thankfully, my colleague had a version of QGC Daily Build that he downloaded earlier that does work. I have attached the binary on the following link. [https://drive.google.com/file/d/1abWLMGlYi5QoL5Aphgi1p6Qsrqc0upkv/view?usp=sharing](https://drive.google.com/file/d/1abWLMGlYi5QoL5Aphgi1p6Qsrqc0upkv/view?usp=sharing)

Do let me know if this resolved your issue.

**Comment by kousheekc** [comment]
Hi @votmA , curious to know if the above mentioned version of QGroundControl Daily build solved your issue. Also, since this issue was originally related to "Launch error" and that seems to be resolved by selecting appropriate versions of px4-ros2-interface-lib and px4_msgs, I am closing this issue. If the QGroundControl issue persists, I suggest to open a new issue with that topic.

**Comment by votmA** [comment]
Hi @kousheekc ! Sorry for late response. Thank you very much for daily build. It is indeed has an ability to switch to a custom mode.
However, I have not managed to launch it anyway. Some error from interface lib is popping up. I will further investigate it. And I will let you know if I finally will launch something.
